server:
    port: 8000

spring:
    application:
      name: spring-cloud-eureka

eureka:
    instance:
        hostname: localhost
    client:
        #是否将自己注册到Eureka Server，默认为true
        register-with-eureka: false
        #是否从Eureka Server获取注册信息，默认为true
        fetch-registry: false
        serviceUrl:
            #服务注册的URL
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/